# Makefile generated automatically
all: SocialNetwork.exe
SocialNetwork.exe:  main.o SocialNetwork.o Group.o Person.o
	g++ -Wall -g -o SocialNetwork.exe main.o SocialNetwork.o Group.o Person.o
main.o:  main.cpp
	g++ -c -Wall -g SocialNetwork.h main.cpp
SocialNetwork.o:  SocialNetwork.cpp
	g++ -c -Wall -g SocialNetwork.h SocialNetwork.cpp
Group.o:  Group.cpp
	g++ -c -Wall -g Group.h Group.cpp
Person.o:  Person.cpp
	g++ -c -Wall -g Person.h Person.cpp
