# Makefile generated automatically
all: Josephine.exe
Josephine.exe:  Josephine.o DataStructure.o
	g++ -Wall -g -o Josephine.exe Josephine.o DataStructure.o
Josephine.o:  Josephine.cpp
	g++ -c -Wall -g Josephine.cpp
DataStructure.o:  DataStructure.cpp
	g++ -c -Wall -g DataStructure.cpp
