# Makefile Warriorerated automatically
all: Warrior.exe
Warrior.exe:  Warrior.o 
	/usr/sfw/bin/g++ -Wall -g -o Warrior.exe Warrior.o 
Warrior.o:  Warrior.cpp
	/usr/sfw/bin/g++ -c -Wall -g Warrior.cpp
