# Makefile generated automatically
all: FileOrganization.exe
FileOrganization.exe:  main.o Folder.o File.o
	g++ -Wall -g -o FileOrganization.exe main.o Folder.o File.o
main.o:  main.cpp
	g++ -c -Wall -g main.cpp
Folder.o:  Folder.cpp
	g++ -c -Wall -g Folder.cpp
File.o:  File.cpp
	g++ -c -Wall -g File.cpp
