# Makefile Incantationerated automatically
all: Incantation.exe
Incantation.exe:  Incantation.o 
	/usr/sfw/bin/g++ -Wall -g -o Incantation.exe Incantation.o 
Incantation.o:  Incantation.cpp
	/usr/sfw/bin/g++ -c -Wall -g Incantation.cpp
